linker = "/usr/bin/x86_64-w64-mingw32-gcc"
ar = "/usr/bin/x86_64-w64-mingw32-gcc-ar"

database_url = "sqlite://example.db"
server_port = 3047

save_path = ""
game_path = ""
mod_paths = [""]

language = "chinese"